In [2]:
import numpy as np

In [3]:
ones = np.ones((5,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
randones = np.random.beta(ones[:, 0], ones[:, 1])
idx = np.argmax(np.random.beta(ones[:, 0], ones[:, 1]))
idx

2

In [5]:
pulled_arm = idx
pulled_arm

2

In [36]:
probabilities = np.array([0.40, 0.3, 0.1, 0.35])
n_arms = len(probabilities)
n_arms

4

In [1]:
reward = np.random.binomial(1, probabilities[pulled_arm])
reward

NameError: name 'np' is not defined

In [37]:
empirical_means = np.zeros(n_arms)
empirical_means

array([0., 0., 0., 0.])

In [39]:
confidence = np.array([np.inf]*n_arms)
confidence

array([inf, inf, inf, inf])

In [ ]:
np.random.choice(np.where(upper_conf == upper_conf.max())[0])