In [1]:
import numpy as np

In [2]:
ones = np.ones((5,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
randones = np.random.beta(ones[:, 0], ones[:, 1])
idx = np.argmax(np.random.beta(ones[:, 0], ones[:, 1]))
idx

2

In [5]:
pulled_arm = idx
pulled_arm

2

In [6]:
probabilities = np.array([0.40, 0.3, 0.1, 0.35])
n_arms = len(probabilities)
n_arms

4

In [22]:
reward = np.random.binomial(1, probabilities[pulled_arm])
reward

1

In [23]:
empirical_means = np.zeros(n_arms)
empirical_means

array([0., 0., 0., 0.])

In [24]:
confidence = np.array([np.inf]*n_arms)
confidence

array([inf, inf, inf, inf])

In [30]:
randbeta = np.random.beta(ones[:, 0], ones[:, 1])
randbeta

array([0.8147875 , 0.30521836, 0.86537789, 0.02621889, 0.56037892])

In [31]:
idx = np.argmax(randbeta)
idx

2